CMTPATH=/home/liujy/juno/offline:/home/liujy/juno/sniper:/home/liujy/juno/ExternalInterface
CMT_tag=$(tag)
CMTROOT=/home/liujy/juno/ExternalLibs/CMT/v1r26
CMT_root=/home/liujy/juno/ExternalLibs/CMT/v1r26
CMTVERSION=v1r26
CMT_offset=/home/liujy/juno/ExternalLibs
cmt_hardware_query_command=uname -m
cmt_hardware=`$(cmt_hardware_query_command)`
cmt_system_version_query_command=${CMTROOT}/mgr/cmt_linux_version.sh | ${CMTROOT}/mgr/cmt_filter_version.sh
cmt_system_version=`$(cmt_system_version_query_command)`
cmt_compiler_version_query_command=${CMTROOT}/mgr/cmt_gcc_version.sh | ${CMTROOT}/mgr/cmt_filter3_version.sh
cmt_compiler_version=`$(cmt_compiler_version_query_command)`
PATH=/home/liujy/juno/offline/InstallArea/${CMTCONFIG}/bin:/home/liujy/juno/sniper/InstallArea/${CMTCONFIG}/bin:/home/liujy/juno/ExternalLibs/CMT/v1r26/${CMTBIN}:/home/liujy/mongo-cxx-driver-legacy-1.0.0-rc0/build/install/bin:/home/liujy/juno/ExternalLibs/Xercesc/3.1.1/bin:/home/liujy/juno/ExternalLibs/ROOT/5.34.11/bin:/home/liujy/juno/ExternalLibs/Python/2.7.6/bin:/home/liujy/juno/ExternalLibs/GCCXML/master/bin:/home/liujy/juno/ExternalLibs/CLHEP/2.1.0.1/bin:/home/liujy/juno/ExternalLibs/Boost/1.55.0/bin:/usr/local/hadoop/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/jvm/java-6-oracle/bin:/usr/lib/jvm/java-6-oracle/db/bin:/usr/lib/jvm/java-6-oracle/jre/bin
CLASSPATH=/home/liujy/juno/ExternalLibs/CMT/v1r26/java
debug_option=-g
cc=gcc
ccomp=$(cc) -c $(includes) $(cdebugflags) $(cflags) $(pp_cflags)
clink=$(cc) $(clinkflags) $(cdebugflags)
ppcmd=-I
preproc=c++ -MD -c 
cpp=g++
cppflags=-fPIC -pipe -ansi -W -Wall -Wwrite-strings -Wpointer-arith -Woverloaded-virtual 
pp_cppflags=-D_GNU_SOURCE
cppcomp=$(cpp) -c $(includes) $(cppdebugflags) $(cppflags) $(pp_cppflags)
cpplink=$(cpp) $(cpplinkflags) $(cppdebugflags)
for=g77
fflags=$(debug_option)
fcomp=$(for) -c $(fincludes) $(fflags) $(pp_fflags)
flink=$(for) $(flinkflags)
javacomp=javac -classpath $(src):$(CLASSPATH) 
javacopy=cp
jar=jar
X11_cflags=-I/usr/include
Xm_cflags=-I/usr/include
X_linkopts=-L/usr/X11R6/lib -lXm -lXt -lXext -lX11 -lm
lex=lex $(lexflags)
yaccflags= -l -d 
yacc=yacc $(yaccflags)
ar=ar cr
ranlib=ranlib
make_shlib=${CMTROOT}/mgr/cmt_make_shlib_common.sh extract
shlibsuffix=so
shlibbuilder=g++ $(cmt_installarea_linkopts) 
shlibflags=-shared
symlink=/bin/ln -fs 
symunlink=/bin/rm -f 
library_install_command=python $(SniperPolicy_root)/cmt/fragments/install.py -xCVS -x.svn -x*~ -x*.stamp -s --log=./install.history 
build_library_links=$(cmtexe) build library_links -tag=$(tags)
remove_library_links=$(cmtexe) remove library_links -tag=$(tags)
cmtexe=${CMTROOT}/${CMTBIN}/cmt.exe
build_prototype=$(cmtexe) build prototype
build_dependencies=$(cmtexe) -tag=$(tags) build dependencies
build_triggers=$(cmtexe) build triggers
format_dependencies=${CMTROOT}/mgr/cmt_format_deps.sh
implied_library_prefix=-l
SHELL=/bin/sh
q="
src=../src/
doc=../doc/
inc=../src/
mgr=../cmt/
application_suffix=.exe
library_prefix=lib
unlock_command=rm -rf 
lock_name=cmt
lock_suffix=.lock
lock_file=${lock_name}${lock_suffix}
svn_checkout_command=python ${CMTROOT}/mgr/cmt_svn_checkout.py 
gmake_hosts=lx1 rsplus lxtest as7 dxplus ax7 hp2 aleph hp1 hpplus papou1-fe atlas
make_hosts=virgo-control1 rio0a vmpc38a
everywhere=hosts
install_command=python $(SniperPolicy_root)/cmt/fragments/install.py -xCVS -x.svn -x*~ -x*.stamp --log=./install.history 
uninstall_command=python $(SniperPolicy_root)/cmt/fragments/install.py -u --log=./install.history 
cmt_installarea_command=python $(SniperPolicy_root)/cmt/fragments/install.py -xCVS -x.svn -x*~ -x*.stamp -s --log=./install.history 
cmt_uninstallarea_command=/bin/rm -f 
cmt_install_area_command=$(cmt_installarea_command)
cmt_uninstall_area_command=$(cmt_uninstallarea_command)
cmt_install_action=$(CMTROOT)/mgr/cmt_install_action.sh
cmt_installdir_action=$(CMTROOT)/mgr/cmt_installdir_action.sh
cmt_uninstall_action=$(CMTROOT)/mgr/cmt_uninstall_action.sh
cmt_uninstalldir_action=$(CMTROOT)/mgr/cmt_uninstalldir_action.sh
mkdir=mkdir
cmt_cvs_protocol_level=v1r1
cmt_installarea_prefix=InstallArea
CMT_PATH_remove_regexp=/[^/]*/
CMT_PATH_remove_share_regexp=/share/
NEWCMTCONFIG=x86_64-debianjessie/sid-gcc482
MongoDBSvc_tag=$(tag)
MONGODBSVCROOT=/home/liujy/juno/offline/Database/MongoDBSvc
MongoDBSvc_root=/home/liujy/juno/offline/Database/MongoDBSvc
MONGODBSVCVERSION=v0
MongoDBSvc_cmtpath=/home/liujy/juno/offline
MongoDBSvc_offset=Database
MongoDBSvc_project=offline
SniperKernel_tag=$(tag)
SNIPERKERNELROOT=/home/liujy/juno/sniper/SniperKernel
SniperKernel_root=/home/liujy/juno/sniper/SniperKernel
SNIPERKERNELVERSION=v2
SniperKernel_cmtpath=/home/liujy/juno/sniper
SniperKernel_project=sniper
SniperPolicy_tag=$(tag)
SNIPERPOLICYROOT=/home/liujy/juno/sniper/SniperPolicy
SniperPolicy_root=/home/liujy/juno/sniper/SniperPolicy
SNIPERPOLICYVERSION=v0
SniperPolicy_cmtpath=/home/liujy/juno/sniper
SniperPolicy_project=sniper
libraryshr_linkopts=-fPIC -ldl -Wl,--as-needed -Wl,--no-undefined 
application_linkopts=-Wl,--export-dynamic 
BINDIR=$(tag)
remove_command=$(cmt_uninstallarea_command)
Boost_tag=$(tag)
BOOSTROOT=/home/liujy/juno/ExternalInterface/Externals/Boost
Boost_root=/home/liujy/juno/ExternalInterface/Externals/Boost
BOOSTVERSION=v0
Boost_cmtpath=/home/liujy/juno/ExternalInterface
Boost_offset=Externals
Boost_project=ExternalInterface
Python_tag=$(tag)
PYTHONROOT=/home/liujy/juno/ExternalInterface/Externals/Python
Python_root=/home/liujy/juno/ExternalInterface/Externals/Python
PYTHONVERSION=v0
Python_cmtpath=/home/liujy/juno/ExternalInterface
Python_offset=Externals
Python_project=ExternalInterface
Python_linkopts= `pkg-config --libs python` 
Python_cppflags= `pkg-config --cflags python` 
Boost_home=${JUNO_EXTLIB_Boost_HOME}
Boost_linkopts= -L$(Boost_home)/lib  -lboost_python  -lboost_thread  -lboost_regex  -lboost_system 
includes= $(ppcmd)"$(MongoDBSvc_root)"  $(ppcmd)"$(srcdir)" $(ppcmd)"/home/liujy/juno/offline/InstallArea/include" $(ppcmd)"/home/liujy/juno/sniper/InstallArea/include" $(use_includes)
PYTHONPATH=/home/liujy/juno/offline/InstallArea/python:/home/liujy/juno/sniper/InstallArea/python:/home/liujy/juno/offline/InstallArea/Linux-x86_64/lib:/home/liujy/juno/ExternalLibs/ROOT/5.34.11/lib/root
SniperKernel_linkopts= -lSniperKernel  -lSniperPython 
SniperKernel_stamps=${SNIPERKERNELROOT}/${BINDIR}/SniperPython.stamp 
SniperKernel_linker_library=SniperPython
SniperPython_dependencies=SniperKernel
SniperPython_shlibflags= -lSniperKernel 
DatabaseSvc_tag=$(tag)
DATABASESVCROOT=/home/liujy/juno/offline/Database/DatabaseSvc
DatabaseSvc_root=/home/liujy/juno/offline/Database/DatabaseSvc
DATABASESVCVERSION=v0
DatabaseSvc_cmtpath=/home/liujy/juno/offline
DatabaseSvc_offset=Database
DatabaseSvc_project=offline
Mongo_tag=$(tag)
MONGOROOT=/home/liujy/juno/ExternalInterface/Externals/Mongo
Mongo_root=/home/liujy/juno/ExternalInterface/Externals/Mongo
MONGOVERSION=v0
Mongo_cmtpath=/home/liujy/juno/ExternalInterface
Mongo_offset=Externals
Mongo_project=ExternalInterface
Mongo_home=${JUNO_EXTLIB_Mongo_HOME}
Mongo_linkopts= -L$(Mongo_home)/lib -lmongoclient $(Boost_linkopts)
Mongo_cppflag= -I$(Mongo_home)/include 
ROOT_tag=$(tag)
ROOTROOT=/home/liujy/juno/ExternalInterface/Externals/ROOT
ROOT_root=/home/liujy/juno/ExternalInterface/Externals/ROOT
ROOTVERSION=v0
ROOT_cmtpath=/home/liujy/juno/ExternalInterface
ROOT_offset=Externals
ROOT_project=ExternalInterface
ROOT_home=${JUNO_EXTLIB_ROOT_HOME}
ROOT_cppflags=`root-config --cflags` -Wno-long-long 
ROOT_linkopts=`root-config --evelibs`
rootcint="$(ROOT_home)/bin/rootcint"
CLHEP_tag=$(tag)
CLHEPROOT=/home/liujy/juno/ExternalInterface/Externals/CLHEP
CLHEP_root=/home/liujy/juno/ExternalInterface/Externals/CLHEP
CLHEPVERSION=v0
CLHEP_cmtpath=/home/liujy/juno/ExternalInterface
CLHEP_offset=Externals
CLHEP_project=ExternalInterface
CLHEP_linkopts= `clhep-config --libs` 
CLHEP_cppflags= `clhep-config --include` 
MongoDBSvc_linkopts= -lMongoDBSvc 
MongoDBSvc_shlibflags=$(libraryshr_linkopts) $(cmt_installarea_linkopts) $(MongoDBSvc_use_linkopts)
MongoDBSvc_use_linkopts=    $(DatabaseSvc_linkopts)  $(SniperKernel_linkopts)  $(SniperPolicy_linkopts)  $(Mongo_linkopts)  $(Boost_linkopts)  $(Python_linkopts)  $(ROOT_linkopts)  $(CLHEP_linkopts) 
MongoDBSvc_stamps=${MONGODBSVCROOT}/${BINDIR}/MongoDBSvc.stamp 
MongoDBSvc_linker_library=MongoDBSvc
tag=Linux-x86_64
package=MongoDBSvc
version=v0
PACKAGE_ROOT=$(MONGODBSVCROOT)
srcdir=../src
bin=../$(MongoDBSvc_tag)/
javabin=../classes/
mgrdir=cmt
BIN=/home/liujy/juno/offline/Database/MongoDBSvc/Linux-x86_64/
project=offline
cmt_installarea_paths= $(cmt_installarea_prefix)/$(CMTCONFIG)/bin $(sniper_installarea_prefix)/$(CMTCONFIG)/lib $(sniper_installarea_prefix)/share/lib $(sniper_installarea_prefix)/share/bin $(offline_installarea_prefix)/$(CMTCONFIG)/lib $(offline_installarea_prefix)/share/lib $(offline_installarea_prefix)/share/bin
use_linkopts= $(cmt_installarea_linkopts)   $(MongoDBSvc_linkopts)  $(DatabaseSvc_linkopts)  $(SniperKernel_linkopts)  $(SniperPolicy_linkopts)  $(Mongo_linkopts)  $(Boost_linkopts)  $(Python_linkopts)  $(ROOT_linkopts)  $(CLHEP_linkopts) 
ExternalInterface_installarea_prefix=$(cmt_installarea_prefix)
ExternalInterface_installarea_prefix_remove=$(ExternalInterface_installarea_prefix)
LD_LIBRARY_PATH=/home/liujy/juno/offline/InstallArea/${CMTCONFIG}/lib:/home/liujy/juno/sniper/InstallArea/${CMTCONFIG}/lib:/home/liujy/mongo-cxx-driver-legacy-1.0.0-rc0/build/install/lib:/home/liujy/juno/ExternalLibs/Xercesc/3.1.1/lib:/home/liujy/juno/ExternalLibs/ROOT/5.34.11/lib/root:/home/liujy/juno/ExternalLibs/ROOT/5.34.11/lib:/home/liujy/juno/ExternalLibs/Python/2.7.6/lib:/home/liujy/juno/ExternalLibs/GCCXML/master/lib:/home/liujy/juno/ExternalLibs/CMT/v1r26/lib:/home/liujy/juno/ExternalLibs/CLHEP/2.1.0.1/lib:/home/liujy/juno/ExternalLibs/Boost/1.55.0/lib
sniper_installarea_prefix=$(cmt_installarea_prefix)
sniper_installarea_prefix_remove=$(sniper_installarea_prefix)
offline_installarea_prefix=$(cmt_installarea_prefix)
offline_installarea_prefix_remove=$(offline_installarea_prefix)
cmt_installarea_linkopts= -L/home/liujy/juno/offline/$(offline_installarea_prefix)/$(CMTCONFIG)/lib  -L/home/liujy/juno/sniper/$(sniper_installarea_prefix)/$(CMTCONFIG)/lib 
ExternalInterface_home=/home/liujy/juno/ExternalInterface
sniper_home=/home/liujy/juno/sniper
offline_home=/home/liujy/juno/offline
offline_install_include= /home/liujy/juno/offline/$(offline_installarea_prefix)/include 
sniper_install_include= /home/liujy/juno/sniper/$(sniper_installarea_prefix)/include 
ExternalInterface_python_path=$(CMTINSTALLAREA)/$(tag)/lib
sniper_python_path=$(CMTINSTALLAREA)/$(tag)/lib
offline_python_path=$(CMTINSTALLAREA)/$(tag)/lib
sniper_install_python=/home/liujy/juno/sniper/$(sniper_installarea_prefix)/python
offline_install_python=/home/liujy/juno/offline/$(offline_installarea_prefix)/python
CMTINSTALLAREA=/home/liujy/juno/offline/$(cmt_installarea_prefix)
use_requirements=requirements $(CMT_root)/mgr/requirements $(DatabaseSvc_root)/cmt/requirements $(SniperKernel_root)/cmt/requirements $(SniperPolicy_root)/cmt/requirements $(Mongo_root)/cmt/requirements $(Boost_root)/cmt/requirements $(Python_root)/cmt/requirements $(ROOT_root)/cmt/requirements $(CLHEP_root)/cmt/requirements 
use_includes= $(ppcmd)"$(DatabaseSvc_root)/src" $(ppcmd)"$(SniperKernel_root)/src" $(ppcmd)"$(SniperPolicy_root)/src" $(ppcmd)"/home/liujy/mongo-cxx-driver-legacy-1.0.0-rc0/build/install/include" $(ppcmd)"/home/liujy/juno/ExternalLibs/Boost/1.55.0/include" $(ppcmd)"$(Python_root)/src" $(ppcmd)"/home/liujy/juno/ExternalLibs/ROOT/5.34.11/include/root" $(ppcmd)"$(CLHEP_root)/src" 
use_fincludes= $(use_includes)
use_stamps=  $(MongoDBSvc_stamps)  $(DatabaseSvc_stamps)  $(SniperKernel_stamps)  $(SniperPolicy_stamps)  $(Mongo_stamps)  $(Boost_stamps)  $(Python_stamps)  $(ROOT_stamps)  $(CLHEP_stamps) 
use_cflags=  $(MongoDBSvc_cflags)  $(DatabaseSvc_cflags)  $(SniperKernel_cflags)  $(SniperPolicy_cflags)  $(Mongo_cflags)  $(Boost_cflags)  $(Python_cflags)  $(ROOT_cflags)  $(CLHEP_cflags) 
use_pp_cflags=  $(MongoDBSvc_pp_cflags)  $(DatabaseSvc_pp_cflags)  $(SniperKernel_pp_cflags)  $(SniperPolicy_pp_cflags)  $(Mongo_pp_cflags)  $(Boost_pp_cflags)  $(Python_pp_cflags)  $(ROOT_pp_cflags)  $(CLHEP_pp_cflags) 
use_cppflags=  $(MongoDBSvc_cppflags)  $(DatabaseSvc_cppflags)  $(SniperKernel_cppflags)  $(SniperPolicy_cppflags)  $(Mongo_cppflags)  $(Boost_cppflags)  $(Python_cppflags)  $(ROOT_cppflags)  $(CLHEP_cppflags) 
use_pp_cppflags=  $(MongoDBSvc_pp_cppflags)  $(DatabaseSvc_pp_cppflags)  $(SniperKernel_pp_cppflags)  $(SniperPolicy_pp_cppflags)  $(Mongo_pp_cppflags)  $(Boost_pp_cppflags)  $(Python_pp_cppflags)  $(ROOT_pp_cppflags)  $(CLHEP_pp_cppflags) 
use_fflags=  $(MongoDBSvc_fflags)  $(DatabaseSvc_fflags)  $(SniperKernel_fflags)  $(SniperPolicy_fflags)  $(Mongo_fflags)  $(Boost_fflags)  $(Python_fflags)  $(ROOT_fflags)  $(CLHEP_fflags) 
use_pp_fflags=  $(MongoDBSvc_pp_fflags)  $(DatabaseSvc_pp_fflags)  $(SniperKernel_pp_fflags)  $(SniperPolicy_pp_fflags)  $(Mongo_pp_fflags)  $(Boost_pp_fflags)  $(Python_pp_fflags)  $(ROOT_pp_fflags)  $(CLHEP_pp_fflags) 
use_libraries= $(DatabaseSvc_libraries)  $(SniperKernel_libraries)  $(SniperPolicy_libraries)  $(Mongo_libraries)  $(Boost_libraries)  $(Python_libraries)  $(ROOT_libraries)  $(CLHEP_libraries) 
fincludes= $(includes)
install_more_includes_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
MongoDBSvc_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
make_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
constituents= install_more_includes MongoDBSvc 
all_constituents= $(constituents)
constituentsclean= MongoDBSvcclean install_more_includesclean 
all_constituentsclean= $(constituentsclean)
cmt_actions_constituents= make 
cmt_actions_constituentsclean= makeclean 
MongoDBSvcprototype_dependencies= $(MongoDBSvccompile_dependencies)
